double* cross_product(double[],double[]);
double bending_energy();
double bond_harmonic_energy();
double bond_length (int ,int );
double backbone_length(int);
double avg_hgt();
double avg_hgt_sq();
double avg_slider_pos();
int initialize1();
int initialize2();
int initialize3();
int sum_hgt_node();
int avg_hgt_node(int);
int hgt_profile();
int avg_hgt_profile(FILE *,int);
int width_hgt(int);
int bb_hgt(int );
int print_width(FILE *,int);
int print_bb(FILE *,int);
